[settings]
dotfiles.relative_symlinks = true

[dotfiles]
"~/.zshrc" = "zsh/.zshrc"
"~/.config/git" = "git"
"~/.config/ghostty" = "ghostty"
"~/.config/eza" = "eza"
"~/.config/mise" = "mise"
"~/.config/ponytail" = "ponytail"
"~/.config/starship.toml" = "starship/starship.toml"
"~/.config/zed" = "zed"
"~/.agents" = "agents"

[bootstrap.packages]
"brew:cmake" = "latest"
"brew:exiftool" = "latest"
"brew:eza" = "latest"
"brew:ffmpeg" = "latest"
"brew:fzf" = "latest"
"brew:gh" = "latest"
"brew:git" = "latest"
"brew:gnupg" = "latest"
"brew:herdr" = "latest"
"brew:mise" = "latest"
"brew:mole" = "latest"
"brew:ninja" = "latest"
"brew:node" = "latest"
"brew:oxlint" = "latest"
"brew:rust" = "latest"
"brew:starship" = "latest"
"brew:zoxide" = "latest"
"brew:hashicorp/tap/terraform" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:codex" = "latest"
"brew-cask:discord" = "latest"
"brew-cask:figma" = "latest"
"brew-cask:font-geist-mono" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:gcloud-cli" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:granola" = "latest"
"brew-cask:linear" = "latest"
"brew-cask:notion" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:steam" = "latest"
"brew-cask:thaw" = "latest"
"brew-cask:zed" = "latest"

[tasks.bootstrap]
run = "npm install -g @earendil-works/pi-coding-agent agent-browser@0.38.2 corepack superset vercel"

[dotfiles."~/.pi/*.json"]
source = "pi/*.json"

[dotfiles."~/.pi/agent/*"]
source = "pi/agent/*"

[dotfiles."~/.config/herdr/*"]
source = "herdr/*"
